### ISSUE TITLE
STATUS_INVALID_SMB with medium/large file downloads using SMB2Client

### ISSUE THREAD

**Issue by scpc0609** [TalAloni/SMBLibrary#31] opened 2019-08-06 20:02 UTC
I am trying to use SMB2Client for downloading any file using a buffer size of 1K. At random, for large/medium files, the download halts midway, and any subsequent request starts getting STATUS_INVALID_SMB. For very small files, it works fine. My helper method for download goes below:
```
public static void DownloadFile(string shareUncPath, string localFullPath, string user, string password)
{
    SMBLibrary.Client.SMB2Client smbClient = new SMBLibrary.Client.SMB2Client();

    //Connect
    string[] uncPathComponents = shareUncPath.Split(new char[] { '/', '\\' }, StringSplitOptions.RemoveEmptyEntries);
    if (uncPathComponents.Length < 3) throw new Exception("Need UNC Path to a file");
    IPAddress ipAddr = Dns.GetHostEntry(uncPathComponents[0]).AddressList.FirstOrDefault(p => p.AddressFamily == AddressFamily.InterNetwork);
    if (ipAddr == null || smbClient.Connect(ipAddr, SMBTransportType.DirectTCPTransport) == false)
    {
        throw new Exception(NTStatus.STATUS_LOGON_FAILURE.ToString());
    }

    //Login
    NTStatus status = smbClient.Login(string.Empty, user, password);
    if (status != NTStatus.STATUS_SUCCESS)
    {
        throw new Exception(status.ToString());
    }

    //Tree connect to Share
    SMBLibrary.Client.SMB2FileStore fileStore = smbClient.TreeConnect(uncPathComponents[1], out status) as SMBLibrary.Client.SMB2FileStore;
    if (status != NTStatus.STATUS_SUCCESS || fileStore == null)
    {
        throw new Exception(status.ToString());
    }

    // Open existing file for reading
    string srcPath = string.Join("\\", uncPathComponents, 2, uncPathComponents.Length - 2);
    object handle;
    FileStatus fileStatus;
    status = fileStore.CreateFile(out handle, out fileStatus, srcPath, AccessMask.GENERIC_READ, 0, ShareAccess.Read, CreateDisposition.FILE_OPEN, CreateOptions.FILE_NON_DIRECTORY_FILE, null);
    if (status != NTStatus.STATUS_SUCCESS)
    {
        throw new Exception(status.ToString());
    }

    //Retrieve file length / size
    FileInformation fileInfo;
    status = fileStore.GetFileInformation(out fileInfo, handle, FileInformationClass.FileStandardInformation);
    if (status != NTStatus.STATUS_SUCCESS)
    {
        throw new Exception(status.ToString());
    }
    FileStandardInformation fileStdInfo = fileInfo as FileStandardInformation;
    long length = fileStdInfo.EndOfFile;

    //Copy in chunks
    int position = 0;
    using (System.IO.FileStream output = new System.IO.FileStream(localFullPath, System.IO.FileMode.OpenOrCreate, System.IO.FileAccess.Write))
    {
        byte[] buffer;

        do
        {
            int count = (int)Math.Min(1024, length - position);

            status = fileStore.ReadFile(out buffer, handle, position, count);

            if (status == NTStatus.STATUS_END_OF_FILE || buffer?.Length == 0)
            {
                //done
                break;
            }
            else if (status != NTStatus.STATUS_SUCCESS)
            {
                throw new Exception(status.ToString());
            }

            output.Write(buffer, 0, buffer.Length);
            position += buffer.Length;
        }
        while (position < length);
    }
}
```

Using this method is as simple as below. Can be embedded in one of your test for quick check:
```
DownloadFile("\\\\localhost\\Share\\large_300mb_file.zip", "D:\\large_300mb_file.zip", "user", "password");
```

Debugging revealed that there is a response timeout in `WaitForCommand(...)` and it returns `null`, so `STATUS_INVALID_SMB` is being returned from `SMB2FileStore.ReadFile(…)`

```
        public NTStatus ReadFile(out byte[] data, object handle, long offset, int maxCount)
        {
            …
            TrySendCommand(request);
            SMB2Command response = m_client.WaitForCommand(SMB2CommandName.Read);
            if (response != null)
            {
                ...
            }

            return NTStatus.STATUS_INVALID_SMB;
        }
```

I have to use a chunked download of few KBs only as the code may run on low memory devices. This seem to be a problem with protocol handling. Can you please provide some pointers to a fix?

**Comment by TalAloni** [comment] 2019-08-06 20:26
Hi, can you please provide a WireShark packet capture?

**Comment by scpc0609** [comment] 2019-08-07 15:10
Hi TalAloni, thanks for the quick response. I have a capture in the following [link](https://1drv.ms/u/s!Ah76A5ZFb6lgjiJCl3ovhIayCuJg?e=ZsF0xY).

**Comment by TalAloni** [comment] 2019-08-07 18:31
Hi,
I have successfully downloaded a 1.1GB file from a Windows Server 2008 R2 SP2 server using your code without any issues.

I do not see anything suspicious in the packet capture you provided, can you reproduce this issues on other PCs on your network? using different server etc?

In debugging, does the m_incomingQueue contains the packet that the client is waiting for?

**Comment by scpc0609** [comment] 2019-08-07 20:09
Hi TalAloni, 

Thanks for your response. I have checked this in 2 of my laptops running Win 10 Pro 1903 and 1809 respectively, and the log was from a VM running Win 10 Enterprise 1903. Everywhere, it is very consistent when I use the code from a WPF App. I checked again in debugging, and the m_incomingQueue remains empty even if I increase the timeout to a minute.

In the capture I sent, do you see some anomaly around the read response at the end?

**Comment by TalAloni** [comment] 2019-08-08 17:00
How about using the code from a console app?

Since I can't reproduce the issue I strongly suspect that it has something to do with your environment, 
if the queue is empty than it means that the last packet I see in the log does not reach the application.
There is a TCP disconnect (FIN) that the client sends to the server at the end, it looks a bit odd because the library does not disconnect the connection unless specifically requested, but I'm guessing it can happen if you stop the debugger, not sure about that, maybe it's a clue.
Can you try VM to VM? Running the console app on Windows 7 and connecting to a different Windows 7 Server?

**Comment by scpc0609** [comment] 2019-08-09 11:54
Hi TalAloni, I could not reproduce this on a Console app.

As this problem was repeating almost everytime on a GUI app (even with files sized 8-20mb), today I decided to inject some additional logging into the code to get into root of it and seem to have cracked it.

When the problem occurs, the last incoming packet was being rejected from the below code:
```
private void OnClientSocketReceive(IAsyncResult ar)
{
    if (ar != m_currentAsyncResult)
    {
        // We ignore calls for old sockets which we no longer use
        // See: http://rajputyh.blogspot.co.il/2010/04/solve-exception-message-iasyncresult.html
        return;
    }
...
```
If the above return block is commented out, I am able to download large files on the same GUI app without any problem (tested up to 1GB). Also did a compare of the downloaded file with the original one, and verified they have binary match. Commenting out this code might require additional exception handing elsewhere?

Also there could be other potential issues (not the root cause of my problem) on the code like below found in many places:
```
TrySendCommand(request);
SMB2Command response = WaitForCommand(SMB2CommandName.TreeConnect);
```
If we go down the call tree of TrySendCommand, there are a few exit paths where the command will be not sent, as well as there are caught exceptions that are absorbed. This means that the actual command may not have been sent, but the next line would still go for a WaitForCommand without any knowledge. I think it will be appropriate to either propagate exception up the stack or return true / false and WaitForCommand() based on success of TrySendCommand().

**Comment by TalAloni** [comment] 2019-08-10 12:41
Hi,
The code you pointed to was designed to prevent a client from receiving old packets that were sent before Disconnect() and Connect(). I'm not sure if and how it can cause any problems during regular use.
If you can't reproduce this from a console app, it might suggest that the issue has something to do with your host application closing the connection (either explicitly or implicitly).
Try to create the most minimal WPF app and see if the issue is related to WPF or perhaps to something in your project.
Since you were not able to reproduce this in a console app it's likely that the issue is with some WPF setting or something in your project, not with the library itself. I'm closing the issue for now but I'm here to help.

**Comment by scpc0609** [comment] 2019-08-10 13:30
Hi TalAloni, I am broken that you closed this genuine issue even after me furnishing so much details and a fix, and you still continue thinking in context of Console Apps and 2008 Servers.

I have been already trying to use this from minimalistic apps (UWP & WPF), and the code is also given above. The host application is windows 10 SMB services and it is not closing any connection, but your code is rejecting valid packets.
- The reason behind Console and UI app having different behaviors could be due to how the OS handles asynchronous messaging internally for Console and GUI Apps.
- The OnClientSocketReceive callback happens in different threads, and hence your logic to rely on m_currentAsyncResult to reject packet is buggy
- Ideally there should not be any callback after Disconnect, but if it does, then am sure there could be better fixes than what is implemented here

Anyway, I will proceed with my fix, and hope this discussion helps those who wants to use this Library in modern environments.

**Comment by TalAloni** [comment] 2019-08-10 14:51
What you are touting as a "fix" is simply a workaround,
there is a root cause that neither of us currently understand,
Can you share the code of your minimal app?

**Comment by TalAloni** [comment] 2019-08-10 15:02
Looking again at the code, it might be related to thread safety, it's possible that the value of m_currentAsyncResult is set only after the call to BeginReceive and the subsequent call to OnClientSocketReceive.
Can you try using lock (m_currentAsyncResult ) whenever m_currentAsyncResult  is used?

**Comment by scpc0609** [comment] 2019-08-10 15:21
I had already tried that using lock(this) to synchronize access to m_currentAsyncResult whereever it is referenced. That does not solve the problem. Using lock(m_currentAsyncResult) is not appropriate as it is m_currentAsyncResult which is getting re-assigned.
You need to understand that while the client is waiting for a read() response, processing any other  response would change the m_currentAsyncResult and when the read response arrives the packed will be disregarded. You may need to maintain a list like m_currentAsyncResults, or don't use that logic at all and handle disconnect differently.

**Comment by scpc0609** [comment] 2019-08-10 15:40
I was also thinking if the TrySendCommand method should return the MessageID it included in header and pass that on to WaitForCommand as an additional argument to check and pick up the correct response. The counter used to generate the MessageID should also be synchronized across threads.

**Comment by TalAloni** [comment] 2019-08-10 15:44
Can you try defining m_currentAsyncResult as volatile?

**Comment by TalAloni** [comment] 2019-08-10 16:20
I can recreate this issue now, seems to be tied with the fast reply that is associated with localhost communication.

**Comment by TalAloni** [comment] 2019-08-10 18:23
I have pushed the fix, thanks for your help!

**Closed by TalAloni** 2019-08-10 18:23 UTC
