### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by vishwas-trivedi** [TalAloni/SMBLibrary#23] opened 2019-04-18 02:57 UTC
Hello,

I'm trying to build a client application that could perform CRUD operation on files stored on SMB server using .NET Core. I tried code from following issue but always fails, connection is successful though :
https://github.com/TalAloni/SMBLibrary/issues/9

Status Code returned is : SEC_E_INVALID_TOKEN
I'm trying to use SMB2Client from following fork :
https://github.com/j4m3z0r/SmbLibraryStd

Could you please share any sample code that I could use to fix this problem??

**Comment by TalAloni** [comment] 2019-04-18 04:36
This is the place for issues relating to the unmodified version of the library.
please test the latest version and see if the problem is still present.
also, please specify which server you are trying to connect to.

**Comment by TalAloni** [comment] 2019-04-18 04:40
also, please submit a WireShark packet capture using the latest version.

**Comment by vishwas-trivedi** [comment] 2019-04-18 05:36
@TalAloni 
Thank you for the quick response!
Following are the details you asked for :
1. SmbLibraryStd Version : 1.3.4.1 (Latest NuGet version)
2. WireShark Packets : Attached.
[smbSpecific.zip](https://github.com/TalAloni/SMBLibrary/files/3092889/smbSpecific.zip)

3. Server Details : I don't know
     - I just know that it is an external SMB server that I don't have normal access to.
     - I could only access the shared directory nothing else.

I didn't know where else to ask about this problem.
Please help.

Regards,
Vishwas

**Comment by TalAloni** [comment] 2019-04-18 10:13
The problem that is demonstrated in the packet capture was resolved in v1.3.6
You can either contact the author of SmbLibraryStd and ask him to update, or adapt the latest version to .NET Core (which should be easy).

**Closed by TalAloni** 2019-04-18 10:13 UTC
