### ISSUE TITLE
Writing files 2 directories deep, reading files 3 directories deep fails on Linux hosted NFS 

### ISSUE THREAD

**Issue by mentallydetached** [TalAloni/SMBLibrary#128] opened 2022-04-21 23:31 UTC
We have a directory structure like this: 

\\\\share\x\y\z\file.txt 

We are experiencing different behavior depending on the OS of the NFS share and the OS of the Client: 

| | Windows NFS | Linux NFS |
| ----- | ----- | ----- |
| **Windows Client** | All directories read/write | All directories read/write |
| **Linux Client** | All directories read/write | We can’t read past \\\\share\x\y and cannot write past \\\\share\x |

The _status_ we are getting on read and write attempts that are failing is: 
**STATUS_OBJECT_NAME_NOT_FOUND**

``` cs
FileStatus fileStatus; 
status = fileStore.CreateFile(out directoryHandle, out fileStatus, nestedPath, AccessMask.GENERIC_READ, 
    SMBLibrary.FileAttributes.Directory, ShareAccess.Read | ShareAccess.Write, CreateDisposition.FILE_OPEN, 
    CreateOptions.FILE_DIRECTORY_FILE, null); 
```

**Comment by TalAloni** [comment] 2022-04-22 13:59
"STATUS_OBJECT_NAME_NOT_FOUND" likely means here that there is something wrong with the path you provide to "CreateFile" - which you did not specify.
Also - it's not clear what you mean by "Linux Client", do you mean "SMBLibrary" running under Linux? you did not provide enough details for me to understand why you believe that the issue is with SMBLibrary.

**Comment by mentallydetached** [comment] 2022-04-22 19:57
We were trying multiple options, and this seemed to work using the SMBLibrary in Docker (Linux). Can you please advise if these make sense and what the file path conventions are for sub-folders. Should we changing them according to the OS env?

1. Connection changed from DNS to IP address:
``` cs
client.Connect(IPAddress.Parse("nn.nn.nn.nn"), SMBTransportType.DirectTCPTransport);
```
2. In the CreateFile, changed path to "x\\y" from "x/y":
``` cs
status = fileStore.CreateFile(out directoryHandle, out fileStatus, "x\\y", AccessMask.GENERIC_READ, 
    (global::SMBLibrary.FileAttributes)System.IO.FileAttributes.Directory, ShareAccess.Read | 
    ShareAccess.Write, CreateDisposition.FILE_OPEN, CreateOptions.FILE_DIRECTORY_FILE, null);
```

**Comment by TalAloni** [comment] 2022-05-24 04:39
Were you able to resolve the issue?

**Comment by TalAloni** [comment] 2022-07-02 18:39
Closing since no update was provided

**Closed by TalAloni** 2022-07-02 18:39 UTC
